- Sources/API/UI/Style/box_style.h
- Sources/UI/Style/box_style.cpp
- Sources/UI/Style/box_style_impl.cpp
Angled linear gradient backgrounds is implemented based on the CSS linear-gradient function, described here:
https://developer.mozilla.org/en-US/docs/Web/CSS/linear-gradient
A new set_background_gradient() function that accepts an initializer list has been added to allow for more gradient stops to be added into the BoxStyle, replacing some of the less flexible functions within that class. 
Sample:
> Added angles and initializer_list to BoxStyle's gradients.

- Sources/API/UI/Style/box_style.h
- Sources/UI/Style/box_background.h
- Sources/UI/Style/box_style.cpp
- Sources/UI/Style/box_style_impl.cpp
The previous implementation doesn't work on all angles. The new implementation now uses `clan::Angle` and follows the CSS specification; positive angles rotate the direction of the gradient clockwise with 0° pointing upwards (gradient runs from the bottom edge to the top edge of the box). 45° makes he gradient run diagonally from the bottom-left to the top-right, 90° makes the gradient run from left to right, and so on...
> Fixed linear gradient implementation.

- Sources/Core/ErrorReporting/exception_dialog.cpp
- Sources/Core/ErrorReporting/exception_dialog_impl.h
- Sources/Display/Platform/Win32/input_device_provider_win32mouse.cpp
- Sources/Display/Platform/X11/input_device_provider_x11mouse.cpp
- Sources/UI/StandardViews/window_view_impl.cpp
When a window has a different pixel ratio setting, UI elements are scaled accordingly, but mouse positioning events are not. With this change, the mouse position scaling is done on the WindowView class instead of platform-specific InputProvider.
Also included is a fix on ErrorDialog to make ClanLib compile on Linux.
> Fix pointer positioning on UI.

- Sources/D3D/d3d_display_window_provider.cpp
D3D target has an unpleasant feature by default - it seeks for alt+enter
sequence and process it before these messages got dispatched to the
actual program. It comes to a nasty effect of having alt+enter
fullscreen mode without programmer knowing about it.
This is a fix for it.
> Prevent D3D to process alt+enter messages

- Sources/GL/Platform/AGL/opengl_window_provider_agl.h
- Sources/GL/Platform/Android/opengl_window_provider_android.cpp
- Sources/GL/Platform/Android/opengl_window_provider_android.h
- Sources/GL/Platform/GLX/opengl_window_provider_glx.h
- Sources/GL/Platform/OSX/opengl_window_provider_osx.h
- Sources/GL/Platform/OSX/opengl_window_provider_osx.mm
- Sources/GL/Platform/WGL/opengl_window_provider_wgl.h
New virtual method DisplayWindowProvider::toggle_fullscreen() prevents compiling on other platforms than Windows. These dummy implementations should make it compile on other platforms too.
I tested only with Linux, but I tried to obey the coding style of other platforms too, so it shouldn't break anything.
> Dummy implementations of toggle_fullscreen()

- .travis.yml
- Sources/API/Display/Window/display_window.h
- Sources/App/Unix/clanapp.cpp
- Sources/Display/Makefile.am
- Sources/Display/Platform/X11/WMSupport.md
- Sources/Display/Platform/X11/clipboard_x11.cpp
- Sources/Display/Platform/X11/clipboard_x11.h
- Sources/Display/Platform/X11/x11_atoms.cpp
- Sources/Display/Platform/X11/x11_atoms.h
- Sources/Display/Platform/X11/x11_window.cpp
- Sources/Display/Platform/X11/x11_window.h
- configure.ac
Fix basic X and window manager support.
- Reduced the amount of `XMoveResize` calls by caching resize events.
- `Expose` events now cause the window to be immediately painted.
- Fixed AutoConf failure when `--disable-clanSound` is passed.
- Removed obsolete AutoConf tests.
- Dropped support for obsolete window managers and window manager hinting mechanisms.
- Moved all X Atom storage and handling code to a new class `X11Atoms`.
- Restructured X11 window creation code.
- Rewrote window typing / styling code.
- Removed illegal window state querying before window is mapped.
- Fixed and finished get/setters for min/max size.
- Fixed improper frame extents handling and all the quirks behind it.
- Made minimizing, maximizing and restoring update cache values.
- Fixed window mapping and …
> Fix X support

- Sources/Core/System/system.cpp
- Sources/Sound/Platform/Linux/soundoutput_oss.cpp
- configure.ac
Fix two compilation errors when using the musl c library (http://musl-libc.org) on linux. The fix for ARM could alternatively be done by changing the macros in detect_cpu_ext.cpp.
> Fix compilation error with ARM and musl libc

- .gitignore
- Examples/UI/HelloWorld/Sources/helloworld.cpp
- Examples/UI/HelloWorld/Sources/helloworld.h
Delete unused declaration from helloworld.h
Changes in helloworld.cpp to prevent closing main window after
d->dismiss(); on hint window. I believe that there is a more elegant
solution, but it is not in my skill
> HelloWorld example

- Sources/API/UI/StandardViews/label_view.h
- Sources/UI/StandardViews/label_view.cpp
Add default property to `LabelView::set_text(...bool force_no_layout = false)`.
When `force_no_layout = true` there is no invalidates and redraws all windows occurs. It helps to improve performance of user program (at least on MS Windows), for example when it needs to change text inside `bool App::update()`.
There is no changes in the behavior of existing programs.
> Add property to LabelView::set_text(...bool force_no_layout = false)

- Sources/UI/StandardViews/ButtonView/button_view_impl.cpp
- Sources/UI/StandardViews/CheckBoxView/checkbox_view_impl.cpp
- Sources/UI/StandardViews/ListBoxView/listbox_view_impl.cpp
- Sources/UI/StandardViews/RadioButtonView/radiobutton_view_impl.cpp
- Sources/UI/StandardViews/ScrollBarView/scrollbar_view_impl.cpp
- Sources/UI/StandardViews/SliderView/slider_view_impl.cpp
- Sources/UI/StandardViews/SpinView/spin_view_impl.cpp
Now user controls (`ButtonView` and so on) change its state only by left button mouse, but is not by every buttons.
> User controls (ButtonView and so on) change its state only by LBM

- Examples/Display/Thread/Sources/app.cpp
- Examples/Display_Shaders/ShaderEffect/program.cpp
- Examples/Display_Shaders/ShaderEffect/program.h
- Examples/UI/FileDialogs/FileDialogs-vc2015.vcxproj
- Examples/UI/FileDialogs/Sources/app.cpp
- Examples/UI/FileDialogs/Sources/app.h
- Examples/UI/HelloWorld/Sources/helloworld.cpp
- Examples/UI/HelloWorld/Sources/helloworld.h
- Examples/UI/MVC/app.cpp
- Examples/UI/TextureView/Sources/gui.cpp
- Sources/API/UI/StandardViews/checkbox_view.h
- Sources/API/UI/StandardViews/label_view.h
- Sources/API/UI/View/view.h
- Sources/UI/StandardViews/ButtonView/button_view_impl.cpp
- Sources/UI/StandardViews/CheckBoxView/checkbox_view.cpp
- Sources/UI/StandardViews/CheckBoxView/checkbox_view_impl.cpp
- Sources/UI/StandardViews/label_view.cpp
- Sources/UI/TopLevel/TextureWindow/texture_window_impl.cpp
- Sources/UI/View/view.cpp
- Sources/UI/View/view_impl.h
* The old scheme of work - when the state changes (hot/unhot, pressed/checked and so on), next was call `set_needs_layout();`, which led to a recalculation of all sizes and call `Invalidate` for the whole window at the end.
* The new scheme of work - when the state changes there is redrawn once - set `clip_rect`, render parent for update the background under the changed item, then draw the element itself and its children.
The changes made suitable use of UI controls in the applications running on the `clan :: Application :: update()`, because now they do not cause repeated redrawing the entire window.
Before making changes on a laptop with a built-in videocard, the window with multiple controls (`ButtonView`, `CheckBoxView`, `LabelView`) at rest FPS was about 800. After start move the …
> Improved performance UI controls (clan::View and inherited).

- Examples/ThemeAero/Sources/theme.cpp
- Sources/UI/StandardViews/CheckBoxView/checkbox_view_impl.cpp
- Sources/UI/Style/style_background_renderer.cpp
1. When state changes, label style changes too
2. Box for check now are at center left, not in top left.
> CheckBoxView small fixes

- Examples/ThemeAero/Sources/theme.cpp
- Examples/UI/HelloWorld/Sources/helloworld.cpp
- Sources/API/Core/Math/rect.h
- Sources/API/UI/StandardViews/listbox_view.h
- Sources/API/UI/StandardViews/scrollbar_view.h
- Sources/API/UI/StandardViews/slider_view.h
- Sources/API/UI/View/view.h
- Sources/UI/StandardViews/ListBoxView/listbox_view.cpp
- Sources/UI/StandardViews/ListBoxView/listbox_view_impl.cpp
- Sources/UI/StandardViews/RadioButtonView/radiobutton_view_impl.cpp
- Sources/UI/StandardViews/ScrollBarView/scrollbar_view.cpp
- Sources/UI/StandardViews/ScrollBarView/scrollbar_view_impl.cpp
- Sources/UI/StandardViews/ScrollBarView/scrollbar_view_impl.h
- Sources/UI/StandardViews/SliderView/slider_view.cpp
- Sources/UI/StandardViews/SliderView/slider_view_impl.cpp
- Sources/UI/StandardViews/SliderView/slider_view_impl.h
- Sources/UI/StandardViews/scroll_view.cpp
- Sources/UI/View/view.cpp
Bug fixes
* SliderView scroll to the right of the maximum
* Add property `lock_to_line` to the ScrollbarView and remove unwanted effect from sub-pixel renderind in ScrollView when position is not integral.
* Improved off the hot state on release LBM when scroll thumb occured.
* Fix the bug with `draw_without_layout()` when root has padding.
* Fix the bug with `draw_without_layout()` in the ScrollView.
Improvements
* Remove `redraw_without_layout` for `ScrollBarView` due to call Invalidate in real applications as the reactions to the scroll.
* Scroll to selected item in `ListboxView`.
* Improvement behaviour in `SliderView` when dragging thumb.
* `SliderView` make hot after release LBM
* `SliderView` traditional delay.
* `SliderView` now DoubleClick as SingleClick.
* `SliderView` size of …
> UI bug fixes and improvements

- Sources/D3D/sampler_state.h
Adds a const modifier to operator () overloading to correct compilation error C3848 in VS2015.
> Corrects compilation error C3848 in VS2015

- Sources/UI/View/view.cpp
Using empty canvas (with default constructor instead _canvas()_ ) in void View::draw_without_layout() raise a runtime error.
It can be tested with HelloWorld example.
> Bugfix for UI

- Sources/API/UI/StandardViews/text_field_view.h
- Sources/UI/StandardViews/TextFieldView/text_field_view.cpp
- Sources/UI/StandardViews/TextFieldView/text_field_view_impl.h
- Sources/UI/View/view.cpp
Change state of TextView, include cursor blinks, now do not update the whole window.
It can be checked at HelloWorld example. In old version click on TextView, then press and hold keyboard left button. Load of one CPU core will be very high.
In new version there is all more smoothly.
> Improving performance UI

- configure.ac
As of freetype-2.9.1 the freetype-config file no longer gets installed
by default.
See also [Make installation of `freetype-config' optional](http://git.savannah.gnu.org/cgit/freetype/freetype2.git/commit/?id=a7833f26c4ac45cafe1dffdcd7f7dcfd6493161c) commit by freetype upstream.
> Use pkg-config to find freetype.

- Sources/API/Core/IOData/iodevice.h
- Sources/API/Core/IOData/iodevice_provider.h
- Sources/API/Core/System/databuffer.h
- Sources/Core/IOData/file.cpp
- Sources/Core/IOData/iodevice.cpp
- Sources/Core/IOData/iodevice_provider_file.cpp
- Sources/Core/IOData/iodevice_provider_file.h
- Sources/Core/IOData/iodevice_provider_memory.cpp
- Sources/Core/IOData/iodevice_provider_memory.h
- Sources/Core/System/databuffer.cpp
- Sources/Core/Zip/zip_iodevice_fileentry.cpp
- Sources/Core/Zip/zip_iodevice_fileentry.h
I started with `IODevice.cpp` and remade from `int` to `size_t` all the related files. Into subsection `core/zip` did not dive, limited to cosmetics at the interface level. Although there is an unsafe code, for example - forced conversion from `int64_t` to `int`:
```
int64_t pos;
...
int ZipIODevice_FileEntry::get_position() const
{
return (int)pos;
}
```
I do not use zip and will not be able to test its performance. At least it became no worse.
Also did not touch the `seek` functions. Their change is non-trivial and requires separate testing and experience of WinAPI (and others OS). As result - and early and now it is impossible to move the pointer in the file more than 2^31 bytes.
Further, thanks to the code analyzer (PVS) was convinced that it had not added any new problems, and also …
> Remake IODevice from int to size_t

- Sources/Core/IOData/Unix/directory_scanner_unix.cpp
- Sources/Core/IOData/Unix/directory_scanner_unix.h
Refactor DirectoryScanner_Unix::scan
to reduce code duplication
This is going to serve as a base for reworking the `next` method
to not vary from filesystem readdir order.
Note: only slightly tested.
This PR was done while working on reproducible builds for openSUSE.
> Refactor DirectoryScanner_Unix::scan

- Examples/Display_Shaders/Bloom/Resources/bloom_fs.glsl
- Examples/Display_Shaders/Bloom/Resources/bloom_vs.glsl
- Examples/Display_Shaders/Bloom/Resources/gaussian_fs.glsl
- Examples/Display_Shaders/Bloom/Resources/highlights_fs.glsl
- Examples/Display_Shaders/Bloom/Resources/highlights_vs.glsl
- Examples/Display_Shaders/Gaussian/Resources/fragment_shader.glsl
- Examples/Display_Shaders/HSVSprite/Resources/fragment.glsl
- Examples/Display_Shaders/HSVSprite/Resources/vertex.glsl
- Examples/Display_Shaders/NightVision/Resources/fragment_shader.glsl
- Examples/Display_Shaders/PostProcessing/Resources/fragment_shader.glsl
- Examples/Display_Shaders/Shockwave/Resources/fragment_shader.glsl
**Fixed bug description**
I met errors during compilation shader like:
`libc++abi.dylib: terminating with uncaught exception of type clan::Exception: Unable to compile shader program fragment_shader.glsl: ERROR: 0:27: Invalid call of undeclared identifier 'texture2D'`
`libc++abi.dylib: terminating with uncaught exception of type clan::Exception: Unable to compile shader program vertex.glsl: ERROR: 0:2: '' :  #version required and missing.
ERROR: 0:2: 'attribute' : syntax error: syntax error`
**How to reproduce**
I wrote bash script build.sh to build example.
`g++ -std=c++11 -o $1 Sources/*.cpp -Xlinker -v -L../../../Build/lib/osx -lpthread -lclanApp -lclanCore -lclanGL -lclanDisplay -lclanUI -I../../../Build/include -framework OpenGL -framework Cocoa`
Command ./build.sh PostProcessing in …
> Fix shaders in Display_Shaders examples to compile
